export const authConstants = Object.freeze({
  username: "username",
  accessToken: "accessToken",
  refreshToken: "refreshToken",
  role: "role",
  apiUrl: "apiUrl",
  accessTokenExpiration: "accessTokenExpiration",
  refreshTokenExpiration: "refreshTokenExpiration",
  codeId: "codeId",
  resetPassword: "resetPassword",
  forgetPasswordCodeId: "forgetPasswordCodeId",
  loginId: "loginId",
});

export const pathConstants = Object.freeze({
  login: "/login",
  dashboard: "/fix-sessions",
  roles: "/roles",
  assignedUsersByRole: "/roles/assigned-users-by-role",
  unauthorized: "/unauthorized",
});

export const REFRESH_INTERVAL = 60 * 1000; // 1 minute

export const severities = Object.freeze({
  error: "error",
  info: "info",
  success: "success",
  warning: "warning",
});

export const textMessages = Object.freeze({
  unableToCheckConnectivity: "Unable to check connectivity.",
  connectionSuccessful: "The connection was made successfully.",
  userWasCreatedSuccessfully: "User was created successfully.",
  userCanNotBeCreated: "User can not be created.",
  userCanNotBeUpdated: "User can not be updated.",
  areYouSure: "<i>Are you sure?</i>",
  sessionCreatedSuccessfully: "Session created successfully!",
  unableToCreateSession: "Unable to create session!",
  jenkinsConfigurationsWereSavedSuccessfully: "Jenkins configurations were saved successfully.",
  errorInSavingJenkinsConfig: "There was an error in saving jenkins configurations.",
  anErrorOccurred: "An error occurred.",
  fixMessageEmailConfigurationDeleted: "Message email configuration removed successfully.",
});

export const fixMessagesList = Object.freeze([
  "0",
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
  "G",
  "H",
  "J",
  "K",
  "L",
  "M",
  "N",
  "P",
  "Q",
  "R",
  "S",
  "T",
  "V",
  "W",
  "X",
  "Y",
  "Z",
  "a",
  "b",
  "c",
  "d",
  "e",
  "f",
  "g",
  "h",
  "i",
  "j",
  "k",
  "l",
  "m",
]);
